import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
AiFillTwitterCircle,
AiFillLinkedin,
AiFillYoutube,
}
 from 'react-icons/ai';

 import Image from "next/image";
 import deved from "../public/dev-ed-wave.png";
 import design from "../public/design.png";
 import code from "../public/code.png";
 import consulting from "../public/consulting.png";
 import web1 from "../public/web1.png";
 import web2 from "../public/web2.png";
 import web3 from "../public/web3.png";
 import web4 from "../public/web4.png";
 import web5 from "../public/web5.png";
 import web6 from "../public/web6.png";

 import { useState } from "react";
 



export default function Home() {

        const [darkMode,setDarkMode] =useState(false);

return (

<div className={darkMode ? "dark" : ""}>

<Head>

<title>Shakir Jan Portfolio </title>
<meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

</Head>


<main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
<section className="min-h-screen">
<nav className="py-10 mb-12 flex justify-between">
<h1 className="text-xl font-burtons">developedByJan</h1>
<ul className="flex items-center">
<li><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className="cursor-pointer text-2xl" /></li>
<li><a className="bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>

</ul>

</nav>

<div className="text-center p-10">
<h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl"> Shakir Ehwal </h2>
<h3 className="text-2xl py-2 md:text-3xl">Developer and designer.</h3>
<p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
Hello! I'm a passionate React Developer having 3 years of experience in building responsive and dynamic web applications. I'm dedicated to creating engaging user experiences and bringing design concepts to life through code.
</p>
</div>
        
<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 ">
<AiFillLinkedin />
<AiFillTwitterCircle />
<AiFillYoutube />
        
        
</div>      

<div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">

<Image src={deved} layout="fill" objectFit="cover" />

</div>

</section>

<section>

<div>

<h3 className="text-3xl py-1"> Services I offer </h3>
 <p className="text-md py-5 leading-8 text-gray-80">

 <span className="text-teal-500">E-commerce Website for Fashion Retailer: </span> <br />

Description: Redesigned and developed an e-commerce website for XYZ Fashion, featuring a user-friendly interface, product catalog, and secure checkout process.
Role: Lead Developer
Technologies: React, Redux, HTML/CSS, REST API integration
Link: View Live
Duration: April 2023 - June 2023
XYZ Fashion Screenshot

<span className="text-teal-500">Interactive Dashboard for Data Analysis: </span> <br />

Description: Built a dynamic data dashboard for ABC Analytics, allowing users to visualize and analyze complex data sets with interactive charts and filters.
Role: Front-end Developer
Technologies: React, Chart.js, API integration
Link: View Demo
Duration: January 2023 - March 2023
ABC Analytics Dashboard Screenshot        
</p>       

<p className="text-md py-2 leading-8 text-gray-800">
  I offer a wide range of services including programming, website design and teaching.       
</p>
</div>

<div className="lg:flex gap-10" >

<div   className="text-center shadow-lg p-10 rounded-xl my-10">
<Image src={design} width={100} height={100} className="mx-auto"/>
<h3 className="text-lg font-medium  pt-8 pb-2">Beautiful Designs </h3>
<p className="py-2">
Creating elegant designs suited for your needs following core design theory.        
</p>
<h4 className="py-4 text-teal-600">Design tools I use</h4>
<p className="text-gray-800 py-1" >Photoshop</p>
<p className="text-gray-800 py-1" >Illustrator</p>
<p className="text-gray-800 py-1" >Figma</p>
</ div>
 
<div   className="text-center shadow-lg p-10 rounded-xl my-10">
<Image src={consulting} width={100} height={100} className="mx-auto"/>
<h3 className="text-lg font-medium  pt-8 pb-2">Web Developer </h3>
<p className="py-2">
A passionate React developer with a strong dedication to creating exceptional web experiences. With a background in computer science and a love for front-end development, I have following skills.        
</p>
<h4 className="py-4 text-teal-600"> Skills </h4>
<p className="text-gray-800 py-1" >React.js</p>
<p className="text-gray-800 py-1" >JavaScript(ES6+)</p>
<p className="text-gray-800 py-1" >Redux</p>
<p className="text-gray-800 py-1" >HTML5/CSS3</p>
<p className="text-gray-800 py-1" >Git/GitHub</p>
<p className="text-gray-800 py-1" >Responsive Web Design</p>
<p className="text-gray-800 py-1" >UI/UX Design Principles</p>
</ div>

<div   className="text-center shadow-lg p-10 rounded-xl my-10">
<Image src={code} width={100} height={100} className="mx-auto"/>
<h3 className="text-lg font-medium  pt-8 pb-2">At Work </h3>
<p className="py-2">
Excited to present my portfolio showcasing some of my recent projects      
</p>
<h4 className="py-4 text-teal-600">Projects</h4>
<p className="text-gray-800 py-1" >E-commerce Website for Fashion Retailer</p>
<p className="text-gray-800 py-1" >Interactive Dashboard for Data Analysis</p>
<p className="text-gray-800 py-1" >Todo List</p>
</ div>
</div>
</section>

<section>

<div>
<h3 className="text-3xl py-1">Portfolio</h3>

<p className="text-md py-5 leading-8 text-gray-80">

<span className="text-teal-500" > What Sets Me Apart: </span> <br />

<span className="text-blue-500" > Expertise in React: </span> I have a deep understanding of React, leveraging its powerful component-based architecture to create seamless and interactive user interfaces. Whether it's building single-page applications (SPAs) or integrating React into existing projects, I excel in harnessing the full potential of this library.

<span className="text-blue-500" >Next.js Mastery: </span> I'm proficient in Next.js, a versatile framework that combines server-side rendering (SSR), static site generation (SSG), and client-side rendering (CSR) for optimal performance and SEO. My expertise in Next.js enables me to deliver blazing-fast web experiences.

<span className="text-blue-500" >Responsive Design: </span> I prioritize responsive web design, ensuring that applications look and function flawlessly across a wide range of devices and screen sizes. I understand the importance of delivering a consistent user experience.

<span className="text-blue-500" >State Management: </span> Proficient in state management solutions like Redux and the Context API, I efficiently manage application state, enhancing user interactions and maintaining data consistency. <br />

<span className="text-blue-500" >API Integration: </span> I have experience integrating RESTful and GraphQL APIs, enabling seamless data retrieval and interaction with external services and databases. 
</p>      
</div>

<div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">

<div className="basis-1/3 flex-1 ">
<Image src={web1} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
</div>

<div className="basis-1/3 flex-1 ">
<Image src={web2} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
</div>

<div className="basis-1/3 flex-1 ">
<Image src={web3} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
</div>

<div className="basis-1/3 flex-1 ">
<Image src={web4} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
</div>

<div className="basis-1/3 flex-1 ">
<Image src={web5} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
</div>

<div className="basis-1/3 flex-1 ">
<Image src={web6} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive" />
</div>



</div>

</section>




</main>

</div>


);







}